config/routes.rb
Rails.application.routes.draw do
  get 'shredder/index'
  root 'pages#home'

  resources :tests

  resources :textbooks do
    resources :pageimages, only: [:new, :create, :destroy]
  end

  resources :shredder, only: [:index]

  resources 'prints'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/textbook.rb
class Textbook < ApplicationRecord
    has_many :pageimages, dependent: :destroy
    validates :grade, presence: true
    validates :texttitle, presence: true

    enum subject: {
        ja: 0,
        ma: 1,
        hi: 2,
        ge: 3,
        ci: 4,
        sc: 5,
        en: 6,
        other: 7
    }

    enum grade: {
        j3: 0,
        j2: 1,
        j1: 2,
        jh: 3,
        e6: 4,
        e5: 5,
        e4: 6,
        el: 7,
        pre: 8
    }

    enum texttitle: {
        jitsuren: 1,
        keywork: 2,
        hisshu: 3,
        master: 4,
        shinwork: 5,
        yoshuseries: 6,
        othertext: 7

     }

end

app/controllers/textbooks_controller.rb
class TextbooksController < ApplicationController

    def index
      @textbooks = Textbook.all.order(:grade, :subject, :texttitle, :notes)
      @textbooks = @textbooks.where(grade: params[:grade]) if params[:grade].present?
      @textbooks = @textbooks.where(subject: params[:subject]) if params[:subject].present?
      @textbooks = @textbooks.where(texttitle: params[:texttitle]) if params[:texttitle].present?

    end

    def show
        @textbook = Textbook.find(params[:id])
        @pageimages = @textbook.pageimages.order(:title)
    end

    def new
        @textbook = Textbook.build
    end

    def create
      @textbook = Textbook.build(textbook_params)
      if @textbook.save
        redirect_to @textbook, notice: 'テキストが正常に作成されました。'
      else
        flash[:error] = 'ページ画像の登録中にエラーが発生しました。'
        render :new
      end
     end

     def edit
      @textbook = Textbook.find(params[:id])
    end

    def update
      @textbook = Textbook.find(params[:id])
      if @textbook.update(textbook_params)
        redirect_to @textbook, notice: '編集が完了しました。'
      else
        render :edit
      end
    end

    def destroy
      textbook = Textbook.find(params[:id])
      textbook.destroy!
      redirect_to shredder_index_path, notice: '削除されました。'
    end

    private

    def textbook_params
      params.require(:textbook).permit(:subject, :grade, :texttitle, :notes)
    end

end

app/helpers/textbooks_helper.rb
module TextbooksHelper
end

app/views/textbooks/_form.html.haml
.row.justify-content-center
  .col-md-6.text-start
    = form_with model: @textbook, local: true, html: { class: "needs-validation", novalidate: "" } do |form|
      .form-group.my-3
        = form.label :subject, "◾️科目"
        = form.select :subject, Textbook.subjects.keys.map { |k| [human_enum_name('textbook', 'subject', k), k] }, {}, { class: 'form-control' }
  
      .form-group.my-3
        = form.label :grade, "◾️学年"
        = form.select :grade, Textbook.grades.keys.map { |k| [human_enum_name('textbook', 'grade', k), k] }, {}, { class: 'form-control' }
  
      .form-group.my-3
        = form.label :texttitle, "◾️テキスト名"
        = form.select :texttitle, Textbook.texttitles.keys.map { |k| [human_enum_name('textbook', 'texttitle', k), k] }, {}, { class: 'form-control' }
  
      .form-group.my-3
        = form.label :notes, "◾️備考・その他のテキストの場合はテキスト名"
        = form.text_area :notes, class: "form-control"
    
    
      = form.submit "登録", class: "btn btn-primary button-class mt-3"
    = link_to "戻る", textbooks_path, class: "btn btn-secondary button-class my-5"

app/views/textbooks/edit.html.haml
.container.pb-5
  .text-end
    %h1.display-4.font-weight-bold.mt-4 EditTextbook
    %p.lead テキスト情報編集
    %hr

    = render 'form'

app/views/textbooks/index.html.haml
.container.pb-5
    .text-end
        %h1.display-4.font-weight-bold.mt-4 Textbooks
        %p.lead テキストの答え
        %hr.mb-5



    =link_to new_textbook_path do
        .btn.btn-danger.my-1.p-3 　新しい模範解答を追加　





    
    %hr
    .text-center
        %p.lead.fw-bold 検索
    %hr

    
    = form_tag textbooks_path, method: :get do
        .form-group
            = label_tag :grade, "◾️学年", class: "fw-bold mb-2"
            = select_tag :grade, options_for_select([["中３", 0], ["中２", 1], ["中１", 2], ["中学生共通", 3], ["小６", 4], ["小５", 5], ["小４", 6], ["小学生共通", 7], ["リトルプレ", 8]]), prompt: "すべて", class: "form-control"
        .form-group.mt-3
            = label_tag :subject, "◾️教科", class: "fw-bold mb-2"
            = select_tag :subject, options_for_select([["国語", 0], ["数学or算数", 1], ["歴史", 2], ["地理", 3], ["公民or社会", 4], ["理科", 5], ["英語", 6], ["その他", 7]]), prompt: "すべて", class: "form-control"
        .form-group.mt-3.mb-3
            = label_tag :texttitle, "◾️テキスト", class: "fw-bold mb-2"
            = select_tag :texttitle, options_for_select([["実力練成", 1], ["Keyワーク", 2], ["必修テキスト", 3], ["教科書マスター", 4], ["新ワーク", 5], ["予習シリーズ系", 6], ["その他", 7]]), prompt: "すべて", class: "form-control"

        
        = submit_tag "　　検索　　", class: "btn btn-primary mt-4 button-class"


    %hr.mt-5
    .text-center
        %p.lead.fw-bold 検索結果
    %hr
    .row.row-cols-1.row-cols-md-4.mb-5
        - @textbooks.each do |textbook|
            - card_color_class = "bg-light" # デフォルトの背景色を設定

            - if textbook.subject == "ja"
                - card_color_class = "color-ja"
            - elsif textbook.subject == "ma"
                - card_color_class = "color-ma"
            - elsif textbook.subject == "hi"
                - card_color_class = "color-hi"
            - elsif textbook.subject == "ge"
                - card_color_class = "color-ge"
            - elsif textbook.subject == "ci"
                - card_color_class = "color-ss"
            - elsif textbook.subject == "sc"
                - card_color_class = "color-sc"
            - elsif textbook.subject == "en"
                - card_color_class = "color-en"
            
            = link_to textbook_path(textbook) do
                .col
                    .card.mt-4{class: card_color_class}
                        .card-body
                            %h4.card-title
                                - if textbook.texttitle == 'othertext'
                                    = textbook.notes
                                - else
                                    = I18n.t("activerecord.attributes.textbook.texttitle.#{textbook.texttitle}")
                            %p.card-text
                            %strong= I18n.t("activerecord.attributes.textbook.grade.#{textbook.grade}")
                            %strong= I18n.t("activerecord.attributes.textbook.subject.#{textbook.subject}")

app/views/textbooks/new.html.haml
.container.pb-5
  .text-end
    %h1.display-4.font-weight-bold.mt-4 NewTextbook
    %p.lead 新規テキストを登録
    %hr

    = render 'form'

app/views/textbooks/show.html.haml
.container
  .row.justify-content-center.mt-5
    
    .text-end
      -if @textbook.texttitle === 'othertext'
        %h1.fw-bold #{@textbook.notes} #{I18n.t("activerecord.attributes.textbook.grade.#{@textbook.grade}")}   #{I18n.t("activerecord.attributes.textbook.subject.#{@textbook.subject}")}
      -else
        %h1.fw-bold #{I18n.t("activerecord.attributes.textbook.texttitle.#{@textbook.texttitle}")} #{I18n.t("activerecord.attributes.textbook.grade.#{@textbook.grade}")}   #{I18n.t("activerecord.attributes.textbook.subject.#{@textbook.subject}")}

      
    .text-center
      %hr        
      %p.lead.fw-bold 目次
      %hr
        .row.row-cols-auto
          - @textbook.pageimages.order(:title).each_with_index do |pageimage, index|
            .btn.btn-light.m-2
              %a(href="#pageimage_#{index + 1}")
                =pageimage.title


.text-center
  %hr        
  %p.lead.fw-bold 模範解答
  %hr


- @pageimages.each_with_index do |pageimage, index|
  .d-flex.justify-content-between.container
    %h3.ms-3= pageimage.title
    
    = form_with(model: [@textbook, pageimage], method: :delete, local: false, data: { turbo_confirm: "本当に削除しますか？" }) do |form|
      = form.submit "削除", class: "btn btn-danger" 
    

  - if pageimage.image.attached?
    = cl_image_tag(pageimage.image.key, id: "pageimage_#{index + 1}", class: 'mb-3 w-100')

    -#= image_tag pageimage.image, id: "pageimage_#{index + 1}", class: 'mb-3 w-100'

.container.px-4
  .row.justify-content-center.mt-5
    = link_to '新しいページ画像を追加', new_textbook_pageimage_path(@textbook), class: 'btn btn-primary my-3'
    

    = link_to "編集", edit_textbook_path(@textbook), class: "btn btn-success mb-3"
    = link_to "戻る", textbooks_path, class: "btn btn-secondary mb-5"