config/routes.rb
Rails.application.routes.draw do
  get 'shredder/index'
  root 'pages#home'

  resources :tests

  resources :textbooks do
    resources :pageimages, only: [:new, :create, :destroy]
  end

  resources :shredder, only: [:index]

  resources 'prints'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/print.rb
class Print < ApplicationRecord

    validates :grade, presence: true
    validates :subject, presence: true
    validates :title, presence: true

    has_many_attached :print_images

    enum subject: {
        ja: 0,
        ma: 1,
        hi: 2,
        ge: 3,
        ci: 4,
        sc: 5,
        en: 6,
        other: 7,
    }

    enum grade: {
        j3: 0,
        j2: 1,
        j1: 2,
        jh: 3,
        e6: 4,
        e5: 5,
        e4: 6,
        el: 7,
        pre: 8
    }

end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController

    def index
      @prints = Print.all.order(:grade, :subject, :title)
      @prints = @prints.where(subject: params[:subject]) if params[:subject].present?
      @prints = @prints.where(grade: params[:grade]) if params[:grade].present?
    end

    def new
        @print = Print.build
    end

    def create
        @print = Print.build(print_params)
        if @print.save
          redirect_to @print, notice: 'テストが正常に作成されました。'
        else
          flash[:error] = 'ページ画像の登録中にエラーが発生しました。'
          render :new
        end
    end

    def edit
      @print = Print.find(params[:id])
    end

    def update
      @print = Print.find(params[:id])

      if params[:print][:print_images].reject(&:blank?).blank?
        update_params = print_params.except(:print_images)
      else
        update_params = print_params
      end

      if @print.update(update_params)
        redirect_to @print, notice: '更新されました'
      else
        render :edit
      end

    end

#    def update
#      @print = Print.find(params[:id])
#
#      # 画像ファイルがアップロードされた場合のみ画像を更新
#      if print_params[print_images: []].present?
#        @print.image.attach(print_params[print_images: []])
#      end
#
#      # その他の属性を更新
#      if @print.update(print_params.except(print_images: []))
#        redirect_to @print, notice: 'テキストが更新されました。'
#      else
#        render :edit
#      end
#
#    end

    def show
        @print = Print.find(params[:id])
    end

    def destroy
      print = Print.find(params[:id])
      print.destroy!
      redirect_to shredder_index_path, notice: '削除されました。'
    end

    private

    def print_params
      params.require(:print).permit(:subject, :grade, :title, :notes, print_images: [])
    end
  end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/views/prints/_form.html.haml
.row.justify-content-center
  .col-md-6.text-start
    = form_with model: print, local: true, html: { class: "needs-validation", novalidate: "" } do |form|
      .form-group.my-3
        = form.label :subject,"◾️教科", class: 'form-label'
        = form.select :subject, Print.subjects.keys.map { |k| [human_enum_name('print', 'subject', k), k] }, {}, { class: 'form-control' }
      .form-group.my-3
        = form.label :grade,"◾️学年", class: 'form-label'
        = form.select :grade, Print.grades.keys.map { |k| [human_enum_name('print', 'grade', k), k] }, {}, { class: 'form-control' }
      .form-group.my-3
        = form.label :title,"◾️プリント名など", class: 'form-label'
        = form.text_area :title, class: 'form-control'
      .form-group.my-3
        = form.label :notes,"◾️備考", class: 'form-label'
        = form.text_area :notes, class: 'form-control'
        
      
    
      .form-group.my-3
        = form.label :print_images,"◾️画像", class: 'form-label'
        = form.file_field :print_images, multiple: true, name: 'print[print_images][]', class: 'form-control'
        
      = form.submit "登録", class: 'btn btn-primary mt-3 form-control mt-5 mb-5 button-class '
      = link_to "戻る", prints_path, class: "btn btn-secondary button-class my-5"



  



        

app/views/prints/edit.html.haml
- if @print.errors.any?
  #error_explanation
    %h2
      = pluralize(@print.errors.count, "error")
      prohibited this print from being saved:
    %ul
      - @print.errors.full_messages.each do |message|
        %li= message

.container
  .text-end
    %h1.display-4.font-weight-bold.mt-4 EditOtherAnswers
    %p.lead 模範解答を編集する
    %hr

  = render 'form' , print: @print

app/views/prints/index.html.haml
.container.pb-5
    .text-end
        %h1.display-4.font-weight-bold.mt-4 Others
        %p.lead プリントなど、その他の答え
        %hr.mb-5



    =link_to new_print_path do
        .btn.btn-danger.my-1.p-3 　新しい模範解答を追加　
    
    %hr
    .text-center
        %p.lead.fw-bold 検索
    %hr

    = form_tag prints_path, method: :get do
        .form-group
            = label_tag :grade, "◾️学年", class: "fw-bold mb-2"
            = select_tag :grade, options_for_select([["中３", 0], ["中２", 1], ["中１", 2], ["中学生共通", 3], ["小６", 4], ["小５", 5], ["小４", 6], ["小学生共通", 7], ["リトルプレ", 8]]), prompt: "すべて", class: "form-control"
        .form-group.mt-3.mb-3
            = label_tag :subject, "◾️教科", class: "fw-bold mb-2"
            = select_tag :subject, options_for_select([["国語", 0], ["数学or算数", 1], ["歴史", 2], ["地理", 3], ["公民or社会", 4], ["理科", 5], ["英語", 6], ["その他", 7]]), prompt: "すべて", class: "form-control"
        
        = submit_tag "　　検索　　", class: "btn btn-primary mt-4 button-class"
      

    %hr.mt-5
    .text-center
        %p.lead.fw-bold 検索結果
    %hr

    .row.row-cols-1.row-cols-md-4.mb-5
        - @prints.each do |print|
            - card_color_class = "bg-secondary" # デフォルトの背景色を設定

            - if print.subject == "ja"
                - card_color_class = "color-ja"
            - elsif print.subject == "ma"
                - card_color_class = "color-ma"
            - elsif print.subject == "hi"
                - card_color_class = "color-hi"
            - elsif print.subject == "ge"
                - card_color_class = "color-ge"
            - elsif print.subject == "ci"
                - card_color_class = "color-ss"
            - elsif print.subject == "sc"
                - card_color_class = "color-sc"
            - elsif print.subject == "en"
                - card_color_class = "color-en"
            
            = link_to print_path(print) do
                .col
                    .card.mt-4{class: card_color_class}
                        .card-body
                            %h4.card-title= print.title
                            %p.card-text
                            %strong= I18n.t("activerecord.attributes.print.grade.#{print.grade}")
                            %strong= I18n.t("activerecord.attributes.print.subject.#{print.subject}")

app/views/prints/new.html.haml
- if @print.errors.any?
  #error_explanation
    %h2
      = pluralize(@print.errors.count, "error")
      prohibited this print from being saved:
    %ul
      - @print.errors.full_messages.each do |message|
        %li= message

.container
  .text-end
    %h1.display-4.font-weight-bold.mt-4 NewOtherAnswers
    %p.lead 新しい模範解答を登録する
    %hr

  .row.justify-content-center
    .col-md-6.text-start

      = form_with model: @print, local: true, html: { class: "needs-validation", novalidate: "" } do |form|
        .form-group.my-3
          = form.label :subject,"◾️教科", class: 'form-label'
          = form.select :subject, Print.subjects.keys.map { |k| [human_enum_name('print', 'subject', k), k] }, {}, { class: 'form-control' }

        .form-group.my-3
          = form.label :grade,"◾️学年", class: 'form-label'
          = form.select :grade, Print.grades.keys.map { |k| [human_enum_name('print', 'grade', k), k] }, {}, { class: 'form-control' }

        .form-group.my-3
          = form.label :title,"◾️プリント名など", class: 'form-label'
          = form.text_area :title, class: 'form-control'

        .form-group.my-3
          = form.label :notes,"◾️備考", class: 'form-label'
          = form.text_area :notes, class: 'form-control'

          
        
      
        .form-group.my-3
          = form.label :print_images,"◾️画像", class: 'form-label'
          = form.file_field :print_images, multiple: true, name: 'print[print_images][]', class: 'form-control'    
          

        = form.submit "登録", class: 'btn btn-primary mt-3 form-control mt-5 mb-5 button-class '

        = link_to "戻る", prints_path, class: "btn btn-secondary button-class my-5"





        

app/views/prints/show.html.haml
.container
  .text-end.mt-5

    .h2.fw-bold
      #{I18n.t("activerecord.attributes.print.grade.#{@print.grade}")} #{human_enum_name('print', 'subject', @print.subject)} 

    .h1.fw-bold
      =@print.title


    %p= @print.notes



- if @print.print_images.attached?
  %hr
  %p.text-center.fw-bold 答案画像
  %hr
  - @print.print_images.each do |image|
    = cl_image_tag(image.blob.key, class: 'max-width')
    -#= image_tag image, class: 'max-width'



.container
  = link_to "編集", edit_print_path(@print), class: "btn btn-success button-class mt-5 mb-3"
  = link_to "戻る", prints_path, class: "btn btn-secondary button-class mb-5"